# This is a basic workflow to help you get started with Actions

name: GitHub Actions Maven Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : Step-1 Checkout Main Branch from GitHub
        uses: actions/checkout@v2

      # Runs a single command to setup JDK 1.8
      - name: Step-2 Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      # Runs a set of commands to package the jar
      - name: Step-3 Have GitHub Actions Maven Build
        run: mvn -B package --file pom.xml
        
      # Runs a set of commands to check the directory
      - name: Step-4 List the current directory
        run: ls
      # Runs a set of commands to check the target directory
      - name: Step-5 List the jar in target directory
        run: 
          cd target;
          ls -a
      # Runs a set of commands to deploy to the Tomcat on EC2 Instance
      - name: Step-6 Deploy to tomcat on EC2 Instance
        run: curl -v -u tomcat:12345 -T /home/runner/work/GitHub_Actions/GitHub_Actions/target/SubmissionDataForm-0.0.1-SNAPSHOT.war 'http://ec2-18-218-175-87.us-east-2.compute.amazonaws.com:8080';
      # Runs a set of commands to deploy to the Tomcat on EC2 Instance
      - name: Step-7 Run the jar
        run: java -jar /home/runner/work/GitHub_Actions/GitHub_Actions/target/SubmissionDataForm-0.0.1-SNAPSHOT.war
