# This is a basic workflow to help you get started with Actions

name: sample

# Controls when the workflow will run
on:
  
  workflow_dispatch:
   inputs:
      hcl:
       description: 'Send for scan'
       required: true
       default: ''

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

   
    steps:
     
      - uses: actions/checkout@v2
      
      - name: Step-4 Zip the Source code
        uses: papeloto/action-zip@v1
        with:
            dest: App.zip
          
    
      - name: Step-5 Verify Directory
        run: dir
        
      - name: Send for Scan
        run: move-Item "App.zip" "D:\Actions" -Force
        if: ${{ github.event.inputs.hcl == 'yes' }}

     
     
