# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
       - name : Step-1 Checkout main branch from GitHub
         uses: actions/checkout@v2
         
       - name: Step-2 Setup JDK 1.8
         uses: actions/setup-java@v1
         with:
            java-version: 1.8
            
       - name: Step-3 Build jar
         run: mvn install
       - name: Step-4 Check directory
         run: dir
       - name: Step-5 deploy to tomcat
         run: curl -v -u tomcat:12345 --upload-file home/runner/work/GitHub_Actions/GitHub_Actions/target/SubmissionDataForm-0.0.1-SNAPSHOT.war "http://ec2-18-218-175-87.us-east-2.compute.amazonaws.com:8080//manager/text/deploy?path=/SpringBoot_SubmissionForm"
         
