# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  
jobs:
  build: 
    name: Deploying war to Tomcat on EC2 Instance

    runs-on: ubuntu-latest

    steps:
    - name: Step:1 Checkout the code
      uses: actions/checkout@v2
      
   # Runs a single command to set up JDK
    - name: Step-2  Setup JDK 1.8
      uses: actions/setup-java@v1
      with: 
          java-version: 1.8
        
    - name: Step:3 Build with Maven
      run: mvn -B package --file pom.xml
     
    - name: Step:4 Check the Directory
      run: ls -a
      
    - name: Step:5 Check target folder
      run:
            cd target;
            ls -a
            
    - name: Step:6 Deploy to Tomcat
      run: curl -u tomcat:12345 -T /home/runner/work/GitHub_Actions/GitHub_Actions/target/SubmissionDataForm-0.0.1-SNAPSHOT.war "http://ec2-13-58-76-208.us-east-2.compute.amazonaws.com:8080/manager/text/deploy?path=/WebApp"
      
