# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  
jobs:
  build: 
    name: Check

    runs-on: self-hosted

    steps:
    - name: Step:1 Checkout the code
      uses: actions/checkout@v2
    
    - run: mkdir -p path/to/artifact
    
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: D:\Actions\world.txt

   
